// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaGrFvyW0dnSgGYesn1sIsUiYKOMXvaJM',
    appId: '1:54885918445:web:baf0a48b442805e6018ee4',
    messagingSenderId: '54885918445',
    projectId: 'notes-app-flutter-e406f',
    authDomain: 'notes-app-flutter-e406f.firebaseapp.com',
    storageBucket: 'notes-app-flutter-e406f.firebasestorage.app',
    measurementId: 'G-849QRMT80X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZy2y55tG5x8-sSzAoJOoQNx9A6POV-g',
    appId: '1:54885918445:android:88f6851af6379e78018ee4',
    messagingSenderId: '54885918445',
    projectId: 'notes-app-flutter-e406f',
    storageBucket: 'notes-app-flutter-e406f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqlfwCS1-SbcefEeTatmCXxllf0yyc2A',
    appId: '1:54885918445:ios:2e63ebd1772b4606018ee4',
    messagingSenderId: '54885918445',
    projectId: 'notes-app-flutter-e406f',
    storageBucket: 'notes-app-flutter-e406f.firebasestorage.app',
    iosBundleId: 'com.example.todoAppHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxqlfwCS1-SbcefEeTatmCXxllf0yyc2A',
    appId: '1:54885918445:ios:2e63ebd1772b4606018ee4',
    messagingSenderId: '54885918445',
    projectId: 'notes-app-flutter-e406f',
    storageBucket: 'notes-app-flutter-e406f.firebasestorage.app',
    iosBundleId: 'com.example.todoAppHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaGrFvyW0dnSgGYesn1sIsUiYKOMXvaJM',
    appId: '1:54885918445:web:8669c7a63a530386018ee4',
    messagingSenderId: '54885918445',
    projectId: 'notes-app-flutter-e406f',
    authDomain: 'notes-app-flutter-e406f.firebaseapp.com',
    storageBucket: 'notes-app-flutter-e406f.firebasestorage.app',
    measurementId: 'G-F9JXR6JQ2H',
  );
}
